export const ENTER_WORKORDER = 'ENTER_WORKORDER'

export const GENERIC_ACTION = 'GENERIC_ACTION'
export const GENERIC_ACTION_2 = 'GENERIC_ACTION_2'

export const POPUP_SUBMIT = 'POPUP_SUBMIT'
export const POPUP_CLOSE =  'POPUP_CLOSE'
export const POPUP_TYPE =  'POPUP_TYPE'
