export const ENTER_WORKORDER = 'ENTER_WORKORDER'

export const GENERIC_ACTION = 'GENERIC_ACTION'
export const GENERIC_ACTION_2 = 'GENERIC_ACTION_2'

export const POPUP_SUBMIT = 'POPUP_SUBMIT'
export const POPUP_CLOSE =  'POPUP_CLOSE'
export const POPUP_TYPE =  'POPUP_TYPE'

export const ADD_SELECTED_EQUIPMENT = 'ADD_SELECTED_EQUIPMENT'
export const REMOVE_SELECTED_EQUIPMENT = 'REMOVE_SELECTED_EQUIPMENT'

export const DIAGRAM_COLLAPSE_SKID_TOGGLE = 'DIAGRAM_COLLAPSE_SKID'
export const DIAGRAM_SHOW_SKID_TOGGLE = 'DIAGRAM_SHOW_SKID'
export const DIAGRAM_SHOW_EQUIPMENT_DETAILS = 'DIAGRAM_SHOW_EQUIPMENT_DETAILS'
export const DIAGRAM_CLUSTER_SELECTED_TOGGLE = 'DIAGRAM_CLUSTER_SELECTED_TOGGLE'
export const DIAGRAM_SET_CLUSTER = 'DIAGRAM_SET_CLUSTER'
